#!/usr/bin/env python3
"""
compdb.py - write the compilation database the IDE indexes Flipso from.

CLion, clangd and anything else that reads a compilation database need to know
how each translation unit is compiled. With no entry for a file the IDE reports
"This file does not belong to any project target" and stops resolving the SDK
headers in it. Flipso has no CMakeLists.txt to derive that from: the firmware is
built by ufbt and the decoder tests by cc. So this collects both halves, plus
the sources that are in neither build, into one compile_commands.json at the
project root, which is where CLion looks for it.

    tools/ide/compdb.py

Then, in CLion, the first time only: right-click compile_commands.json in the
project tree > "Load Compilation Database Project". After that, re-running this
script is picked up by "Reload Compilation Database Project" (or the balloon the
IDE shows when the file changes).

Re-run it after adding a source file or changing the SDK. The output holds
absolute paths into ~/.ufbt, so it is per-machine and stays out of the repo.

Where the entries come from
---------------------------
* Firmware units: ufbt already emits them, into .vscode/compile_commands.json.
* Host units: captured by running tools/test/run.sh with this script standing in
  for the compiler, so the flags cannot drift from what the suite actually uses.
* tools/debug: neither build compiles these - flipso_dump.c is wired in by hand
  for a debugging session (see tools/debug/flipso_dump.h) and crashcanary is a
  separate ufbt project - so they are indexed with the firmware's flags.
"""

from __future__ import annotations

import json
import os
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(os.path.dirname(HERE))
UFBT_DB = os.path.join(PROJECT, ".vscode", "compile_commands.json")
OUTPUT = os.path.join(PROJECT, "compile_commands.json")
RUN_SH = os.path.join(PROJECT, "tools", "test", "run.sh")

# Firmware code that no build compiles; see the module docstring.
UNBUILT = (
    "tools/debug/flipso_dump.c",
    "tools/debug/crashcanary/crashcanary.c",
)

# replay.py compiles this only when it has a card dump to replay, so the capture
# run never sees it. It takes the same flags as the decoder tests, which is what
# replay.py says: "same sanitiser flags as run.sh".
REPLAY = "tools/test/replay.c"


def firmware_units() -> list[dict]:
    """ufbt's own database, generated by `ufbt vscode_dist`."""
    if not os.path.exists(UFBT_DB):
        print("[compdb] no .vscode/compile_commands.json, running ufbt vscode_dist")
        subprocess.run(["ufbt", "vscode_dist"], cwd=PROJECT, check=True)
    with open(UFBT_DB) as f:
        return json.load(f)


def retarget(template: dict, source: str) -> dict:
    """Reuse a firmware command line for a source ufbt never compiled.

    ufbt emits `<gcc> -o <object> -c <flags...> <source>`, so only the two ends
    have to move. Nothing ever runs the result - it exists to be indexed.
    """
    args = shlex.split(template["command"])
    if args[1] != "-o" or args[3] != "-c":
        raise SystemExit(
            "[compdb] ufbt's command line is not '-o <object> -c ... <source>' "
            "any more; retarget() needs updating"
        )
    obj = os.path.join(
        os.path.dirname(args[2]), os.path.basename(source)[:-2] + ".o"
    )
    args[2] = obj
    args[-1] = source
    return {
        "directory": template["directory"],
        "arguments": args,
        "file": source,
        "output": obj,
    }


def retarget_host(template: dict, source: str) -> dict:
    """Reuse a host command line for a unit the capture run did not see."""
    args = [a for a in template["arguments"] if not a.endswith(".c")] + [source]
    return {"directory": template["directory"], "arguments": args, "file": source}


def host_units() -> list[dict]:
    """Run the test suite with this script as $CC and keep what it was asked to compile."""
    tmp = tempfile.mkdtemp(prefix="flipso-compdb.")
    log = os.path.join(tmp, "invocations.jsonl")
    # run.sh word-splits $CC, so it has to be a single argument: point it at a
    # wrapper script rather than at "python3 compdb.py --shim".
    shim = os.path.join(tmp, "cc")
    with open(shim, "w") as f:
        f.write(
            "#!/bin/sh\nexec %s %s --shim \"$@\"\n"
            % (shlex.quote(sys.executable), shlex.quote(os.path.abspath(__file__)))
        )
    os.chmod(shim, os.stat(shim).st_mode | stat.S_IEXEC)

    env = dict(os.environ, CC=shim, FLIPSO_COMPDB_LOG=log)
    # The shim still has to compile for real: run.sh runs each binary it builds,
    # and stops at the first failure.
    env["FLIPSO_COMPDB_CC"] = os.environ.get("CC", "cc")
    print("[compdb] running the host test suite to capture its compiler flags")
    try:
        done = subprocess.run(
            [RUN_SH], env=env, cwd=PROJECT, capture_output=True, text=True
        )
        if done.returncode != 0:
            sys.stdout.write(done.stdout)
            sys.stderr.write(done.stderr)
            raise SystemExit("[compdb] tools/test/run.sh failed; fix the tests first")

        units = []
        with open(log) as f:
            for line in f:
                units.extend(split_invocation(json.loads(line)))
        return units
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def split_invocation(record: dict) -> list[dict]:
    """One test binary is built from several sources; the database wants one entry each."""
    args = record["arguments"]
    sources = [a for a in args if a.endswith(".c")]
    units = []
    for source in sources:
        kept, skip = [], False
        for arg in args:
            if skip:  # the name after -o
                skip = False
                continue
            if arg == "-o":  # an index entry compiles, it does not link
                skip = True
                continue
            if arg.endswith(".c") and arg != source:
                continue
            kept.append(arg)
        kept.insert(1, "-c")
        units.append(
            {
                "directory": record["directory"],
                "arguments": kept,
                "file": os.path.normpath(
                    os.path.join(record["directory"], source)
                ),
            }
        )
    return units


def shim(args: list[str]) -> None:
    """$CC for the test suite: record the invocation, then be the compiler."""
    cc = os.environ.get("FLIPSO_COMPDB_CC") or "cc"
    with open(os.environ["FLIPSO_COMPDB_LOG"], "a") as f:
        f.write(
            json.dumps({"directory": os.getcwd(), "arguments": [cc] + args}) + "\n"
        )
    os.execvp(cc, [cc] + args)


def main() -> None:
    firmware = firmware_units()
    template = next(e for e in firmware if e["file"].endswith("/flipso.c"))
    unbuilt = [retarget(template, os.path.join(PROJECT, p)) for p in UNBUILT]
    host = host_units()
    test_parse = next(u for u in host if u["file"].endswith("/test_parse.c"))
    host.append(retarget_host(test_parse, os.path.join(PROJECT, REPLAY)))

    # A source compiled by both builds - the decoder, the views - is indexed as
    # firmware: those are the flags it ships with. Leaving both in would make
    # the IDE ask which target a file belongs to on every open.
    units, seen = [], set()
    for unit in firmware + unbuilt + host:
        if unit["file"] in seen:
            continue
        seen.add(unit["file"])
        units.append(unit)

    with open(OUTPUT, "w") as f:
        json.dump(units, f, indent=2)
        f.write("\n")
    print(
        "[compdb] wrote compile_commands.json: %d units (%d firmware, %d host)"
        % (len(units), len(firmware) + len(unbuilt), len(units) - len(firmware) - len(unbuilt))
    )

    missing = [p for p in project_sources() if p not in seen]
    if missing:
        print("[compdb] not indexed: " + ", ".join(
            sorted(os.path.relpath(p, PROJECT) for p in missing)))


def project_sources() -> list[str]:
    """Every .c file a person might open, so the summary can flag any left out."""
    found = []
    for root, dirs, names in os.walk(PROJECT):
        dirs[:] = [d for d in dirs if d not in (".venv", ".git", "dist", "build", "__pycache__")]
        found += [os.path.join(root, n) for n in names if n.endswith(".c")]
    return found


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--shim":
        shim(sys.argv[2:])  # execs, never returns
    else:
        main()
